core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(pattern_name="locations:location_list")),
    path("location/", include("locations.urls", namespace="locations")),
]

locations/urls.py
from django.urls import path

from .views import (
    LocationCreateView,
    LocationDetailView,
    LocationListView,
    LocationUpdateView,
    location_delete_view,
)

app_name = "locations"
urlpatterns = [
    path("", LocationListView.as_view(), name="location_list"),
    path("add/", LocationCreateView.as_view(), name="location_create"),
    path("<pk>/", LocationDetailView.as_view(), name="location_detail"),
    path("<pk>/update/", LocationUpdateView.as_view(), name="location_update"),
    path("<pk>/delete/", location_delete_view, name="location_delete"),
]

locations/models.py
from django.db import models
from django.urls import reverse
from djgeojson.fields import PointField


class Location(models.Model):

    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    geom = PointField(null=True)

    class Meta:
        verbose_name = "Location"
        verbose_name_plural = "Locations"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("locations:location_detail", kwargs={"pk": self.id})

    @property
    def popupContent(self):
        url = self.get_absolute_url()
        title_str = '<a class="link link-primary" href="#" '
        title_str += (
            "onclick=\"openLocation('%(url)s')\"><strong>%(title)s</strong></a>"
            % {
                "title": self.title,
                "url": url,
            }
        )
        return {"content": title_str}

locations/forms.py
from django.forms import FloatField, ModelForm, NumberInput

from .models import Location


class LocationCreateForm(ModelForm):
    lat = FloatField(
        label="Latitude", widget=NumberInput(attrs={"max": 90, "min": -90})
    )
    long = FloatField(
        label="Longitude", widget=NumberInput(attrs={"max": 180, "min": -180})
    )

    class Meta:
        model = Location
        fields = ("title", "description")

    def clean(self):
        cleaned_data = super().clean()
        if "lat" not in cleaned_data:
            cleaned_data["lat"] = 0
        if "long" not in cleaned_data:
            cleaned_data["long"] = 0
        lat = cleaned_data["lat"]
        long = cleaned_data["long"]
        if lat > 90 or lat < -90:
            self.add_error("lat", "Invalid value")
        if long > 180 or long < -180:
            self.add_error("long", "Invalid value")
        return cleaned_data

locations/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .forms import LocationCreateForm
from .models import Location


class HtmxMixin:
    """Switches template depending on htmx request header"""

    def get_template_names(self) -> list[str]:
        if (
            "Hx-Request" in self.request.headers
            and self.request.headers["Hx-Request"] == "true"
        ):
            return [self.template_name]
        return [self.template_name.replace("htmx/", "")]


class LocationListView(HtmxMixin, ListView):
    model = Location
    context_object_name = "markers"
    template_name = "locations/htmx/location_list.html"

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        if (
            "Hx-Request" in self.request.headers
            and self.request.headers["Hx-Request"] == "true"
        ):
            dict = {"refreshData": True}
            response["HX-Trigger-After-Swap"] = json.dumps(dict)
        return response


class LocationCreateView(LoginRequiredMixin, HtmxMixin, CreateView):
    model = Location
    template_name = "locations/htmx/location_create.html"
    form_class = LocationCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["markers"] = Location.objects.none()
        context["map_status"] = {"map_on_click": True}
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial["lat"] = 0
        initial["long"] = 0
        return initial

    def form_valid(self, form):
        form.instance.geom = {
            "type": "Point",
            "coordinates": [form.cleaned_data["long"], form.cleaned_data["lat"]],
        }
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("locations:location_detail", kwargs={"pk": self.object.id})

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        if (
            "Hx-Request" in self.request.headers
            and self.request.headers["Hx-Request"] == "true"
        ):
            dict = {"refreshData": True}
            response["HX-Trigger-After-Swap"] = json.dumps(dict)
        return response


class LocationDetailView(HtmxMixin, DetailView):
    model = Location
    template_name = "locations/htmx/location_detail.html"

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        if (
            "Hx-Request" in self.request.headers
            and self.request.headers["Hx-Request"] == "true"
        ):
            dict = {"refreshData": True}
            response["HX-Trigger-After-Swap"] = json.dumps(dict)
            response["HX-Push-Url"] = self.object.get_absolute_url()
        return response


class LocationUpdateView(LoginRequiredMixin, HtmxMixin, UpdateView):
    model = Location
    template_name = "locations/htmx/location_update.html"
    form_class = LocationCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["map_status"] = {"map_on_click": True}
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial["lat"] = self.object.geom["coordinates"][1]
        initial["long"] = self.object.geom["coordinates"][0]
        return initial

    def form_valid(self, form):
        form.instance.geom = {
            "type": "Point",
            "coordinates": [form.cleaned_data["long"], form.cleaned_data["lat"]],
        }
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("locations:location_detail", kwargs={"pk": self.object.id})

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        if (
            "Hx-Request" in self.request.headers
            and self.request.headers["Hx-Request"] == "true"
        ):
            dict = {"refreshData": True}
            response["HX-Trigger-After-Swap"] = json.dumps(dict)
        return response


@login_required
def location_delete_view(request, pk):
    if "Hx-Request" not in request.headers:
        raise Http404("Request without HTMX headers")
    elif not request.headers["Hx-Request"] == "true":
        raise Http404("Request without HTMX headers")
    location = get_object_or_404(Location, id=pk)
    location.delete()
    return TemplateResponse(
        request,
        "locations/htmx/location_delete.html",
        {},
    )

locations/templates/locations/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'locations/css/base.css' %}" rel="stylesheet">
    <title>Map Swap Example</title>
    {% block extra-head %}{% endblock extra-head %}
  </head>
  <body class="d-flex flex-column h-100" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <main class="flex-shrink-0">
      <div id="content" class="container" style="margin-top: 30px">
        {% block content %}
          <h1>Map Swap Example</h1>
        {% endblock content %}
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- Bootstrap bundled JS -->
    <script crossorigin="anonymous" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/htmx.org@2.0.0" integrity="sha384-wS5l5IKJBvK6sPTKa2WZ1js3d947pvWXbPJ1OmWfEuxLgeHcEbjUUA5i9V5ZkpCw" crossorigin="anonymous"></script>
    {% block extra-js %}{% endblock extra-js %}
  </body>
</html>

locations/templates/locations/base_list.html
{% extends "locations/base.html" %}
{% load static %}

{% block extra-head %}
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossorigin=""></script>
{% endblock extra-head %}

{% block content %}
  <div class="row">
    <div class="col" style="margin-bottom: 20px">
      <div class="card" id="dialog-box">
        {% block dialog-box %}
          {% include "locations/htmx/base_list.html" %}
        {% endblock dialog-box %}
      </div>
    </div>
    <div class="col col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
      <div id="swap_map" style="height: 600px; margin-bottom: 20px"></div>
      <script src="{% static 'locations/js/map_script.js'%}"></script>
    </div>
  </div>
{% endblock content %}

locations/templates/locations/htmx/base_list.html
{% load i18n %}
{% load geojson_tags %}

<div class="card-header">
  <h4 class="card-title">{% trans "Locations" %}</h4>
</div>
<div class="card-body">
  {% if markers %}
    <p class="card-text">
      {% blocktrans %}
        Click on the markers and follow the link
        to see the locations in detail.
      {% endblocktrans %}
    </p>
  {% else %}
    <p>{% trans "No locations yet" %}</p>
  {% endif %}
  {% if user.is_authenticated %}
    <a class="btn btn-success"
       hx-get="{% url 'locations:location_create' %}"
       hx-target="#dialog-box"
       hx-push-url="true">
      {% trans "Add location" %}
    </a>
  {% endif %}
</div>
<script id="marker_data" type="application/json">{{ markers|geojsonfeature:"popupContent"|safe }}</script>
{{ map_status|json_script:"map_status" }}

locations/templates/locations/htmx/location_create.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load geojson_tags %}

<div class="card-header">
  <h4 class="card-title">{% trans "Create location"%}</h4>
</div>
<div class="card-body">
  <p class="card-text">
    {% trans "Click on the map to enter coordinates, or enter them manually." %}
  </p>
  <form>
    {{ form|crispy }}
    <button class="btn btn-primary"
            type="submit"
            hx-post="{% url 'locations:location_create' %}"
            hx-target="#hypermedia">
      {% trans "Add location" %}
    </button>
  </form>
</div>
<script id="marker_data" type="application/json">{{ markers|geojsonfeature:"popupContent"|safe }}</script>
{{ map_status|json_script:"map_status" }}

locations/templates/locations/htmx/location_delete.html
{% load i18n %}

<div class="alert alert-danger"
     hx-get="{% url 'locations:location_list' %}"
     hx-target="#hypermedia"
     hx-trigger="load delay:300ms"
     hx-push-url="true">
  {% trans "Deleting..." %}<span class="spinner-border spinner-border-sm"></span>
</div>

locations/templates/locations/htmx/location_detail.html
{% load i18n %}
{% load geojson_tags %}

<div class="card-header">
  <h4 class="card-title">{% trans "Location"%}: {{ object.title }}</h4>
</div>
<div class="card-body">
  <p class="card-text">{{ object.description }}</p>
  <ul>
    {% if user.is_authenticated %}
      <li>
        <a class="link link-primary"
           hx-get="{% url 'locations:location_update' pk=object.id %}"
           hx-target="#hypermedia"
           hx-push-url="true">
          {% trans "Update location" %}
        </a>
      </li>
      <li>
        <a class="link link-danger"
           hx-get="{% url 'locations:location_delete' pk=object.id %}"
           hx-target="#hypermedia"
           hx-confirm="{% trans 'Are you sure you want to delete this location?' %}">
          {% trans "Delete location" %}
        </a>
      </li>
    {% endif %}
    <li>
      <a class="link link-primary"
         hx-get="{% url 'locations:location_list' %}"
         hx-target="#hypermedia"
         hx-push-url="true">
        {% trans "Back to list" %}
      </a>
    </li>
  </ul>
</div>
<script id="marker_data" type="application/json">{{ object|geojsonfeature:"popupContent"|safe }}</script>
{{ map_status|json_script:"map_status" }}

locations/templates/locations/htmx/location_list.html
{% load i18n %}
{% load geojson_tags %}

<div class="card-header">
  <h4 class="card-title">{% trans "Locations" %}</h4>
</div>
<div class="card-body">
  {% if markers %}
    <p class="card-text">
      {% blocktrans %}
        Click on the markers and follow the link
        to see the locations in detail.
      {% endblocktrans %}
    </p>
  {% else %}
    <p>{% trans "No locations yet" %}</p>
  {% endif %}
  {% if user.is_authenticated %}
    <a class="btn btn-success"
       hx-get="{% url 'locations:location_create' %}"
       hx-target="#hypermedia"
       hx-push-url="true">
      {% trans "Add location" %}
    </a>
  {% endif %}
</div>
<script id="marker_data" type="application/json">{{ markers|geojsonfeature:"popupContent"|safe }}</script>
{{ map_status|json_script:"map_status" }}

locations/templates/locations/htmx/location_update.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load geojson_tags %}

<div class="card-header">
  <h4 class="card-title">{% trans "Update location"%}: {{ object.title }}</h4>
</div>
<div class="card-body">
  <p class="card-text">
    {% trans "Click on the map to enter coordinates, or enter them manually." %}
  </p>
  <form>
    {{ form|crispy }}
    <button class="btn btn-primary"
            type="submit"
            hx-post="{% url 'locations:location_update' pk=object.id %}"
            hx-target="#hypermedia">
      {% trans "Update location" %}
    </button>
  </form>
</div>
<script id="marker_data" type="application/json">{{ object|geojsonfeature:"popupContent"|safe }}</script>
{{ map_status|json_script:"map_status" }}

locations/templates/locations/location_create.html
{% extends "locations/location_list.html" %}

{% block hypermedia %}
  {% include "locations/htmx/location_create.html" %}
{% endblock hypermedia %}

locations/templates/locations/location_detail.html
{% extends "locations/location_list.html" %}

{% block hypermedia %}
  {% include "locations/htmx/location_detail.html" %}
{% endblock hypermedia %}

locations/templates/locations/location_list.html
{% extends "locations/base.html" %}
{% load static %}

{% block extra-head %}
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossorigin=""></script>
{% endblock extra-head %}

{% block content %}
  <div class="row">
    <div class="col" style="margin-bottom: 20px">
      <div class="card" id="hypermedia">
        {% block hypermedia %}
          {% include "locations/htmx/location_list.html" %}
        {% endblock hypermedia %}
      </div>
    </div>
    <div class="col col-xl-8 col-lg-8 col-md-12 col-sm-12 col-12">
      <div id="swap_map" style="height: 600px; margin-bottom: 20px"></div>
      <script src="{% static 'locations/js/map_script.js'%}"></script>
    </div>
  </div>
{% endblock content %}

locations/templates/locations/location_update.html
{% extends "locations/location_list.html" %}

{% block hypermedia %}
  {% include "locations/htmx/location_update.html" %}
{% endblock hypermedia %}